{{- if and .Values.openresty.enabled .Values.openresty.autoscaling.enabled (eq .Values.openresty.kind "Deployment") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "forms-waf.fullname" . }}-openresty
  labels:
    {{- include "forms-waf.openresty.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "forms-waf.fullname" . }}-openresty
  minReplicas: {{ .Values.openresty.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.openresty.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.openresty.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.openresty.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.openresty.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.openresty.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
