{{- if .Values.openresty.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forms-waf.fullname" . }}-openresty
  labels:
    {{- include "forms-waf.openresty.labels" . | nindent 4 }}
  {{- if .Values.monitoring.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.openresty.service.metricsPort }}"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: {{ .Values.openresty.service.type }}
  ports:
    - port: {{ .Values.openresty.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.openresty.service.httpsPort | default 8443 }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.openresty.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.openresty.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "forms-waf.openresty.selectorLabels" . | nindent 4 }}
{{- end }}
