{{- if and .Values.openresty.enabled .Values.openresty.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forms-waf.fullname" . }}-openresty
  labels:
    {{- include "forms-waf.openresty.labels" . | nindent 4 }}
spec:
  {{- if .Values.openresty.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.openresty.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.openresty.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.openresty.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "forms-waf.openresty.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if and .Values.haproxy.enabled .Values.haproxy.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forms-waf.fullname" . }}-haproxy
  labels:
    {{- include "forms-waf.haproxy.labels" . | nindent 4 }}
spec:
  {{- if .Values.haproxy.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.haproxy.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.haproxy.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.haproxy.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "forms-waf.haproxy.selectorLabels" . | nindent 6 }}
{{- end }}
