{{- if .Values.openresty.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forms-waf.openresty.serviceAccountName" . }}
  labels:
    {{- include "forms-waf.openresty.labels" . | nindent 4 }}
  {{- with .Values.openresty.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.haproxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forms-waf.haproxy.serviceAccountName" . }}
  labels:
    {{- include "forms-waf.haproxy.labels" . | nindent 4 }}
  {{- with .Values.haproxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
